### ISSUE TITLE
Error on electron:serve

### ISSUE THREAD

**Issue by FelixHoffmannLeanIX** [fazendadosoftware/archimate-mxgraph-mapper#3]
I have cloned the repository, run `npm install` and then tried the `npm run electron:serve`, but then I receive an error message:
![image](https://user-images.githubusercontent.com/26111071/116686995-cfc60280-a9b4-11eb-8726-fde4807229d0.png)

**Comment by pauloramires** [comment]
Can you try to compile it with the latest Node LTS version (v12.13.0)?

**Comment by FelixHoffmannLeanIX** [comment]
@pauloramires Good hint. After updating it worked. Thank you.
